name: WGAN-GP

seed: 42
device: cuda

data_dir: /home/user/PyTorch-Lightning-GAN/GAN/celeba 

z_dim: 128
imsize: 64
img_ch: 3
## gradient penalty coefficient
w_gp: 10
# number of iterations of the discriminator per generator iteration
d_iter_per_g: 5

# learning rate for generator (g) and discriminator (d)
lr:
  g: 1.0e-4
  d: 1.0e-4

batch_size: 256
epochs: 200
# save generated images every save_img_freq epochs
save_image_freq: 20
# save model every save_model_freq epochs
save_model_freq: 50
# saved weights directory
weights_dir: chkpt
# saved images directory
images_dir: images

